### PR TITLE
Write jsonld manifests

### LINKED ISSUE #399: add a few more files to publish
- [ ] add jsonld files (export the json metadata with extension jsonld)
- [ ] create a link (`collection.jsonld`) file that links dandiset id with all the asset ids. (this can be technically recovered from the two files, but would be good to just generate one).

collection.jsonld

```json
{ "@context": <same context as dandiset.jsonld>,
  "id": <same id as dandiset.jsonld>,
  "@type": "prov:Collection", 
  "hasMember": [comma-separated list of "dandiasset:<id>"]
}
```

### PR DESCRIPTION
**Pull request by dchiquito**
Fixes #399

This PR includes some refactoring of the manifest file writing process.
* The task was renamed from `write_yamls` to `write_manifest_files`.
* There is now a `manifests.py` that handles all of the path, URL, and manifest file writing, which used to be spread between `tasks.py` and `models/version.py`.
* There is now a `test_manifests.py` that tests each of the major methods in `manifests.py`.
* The test in `test_tasks` now simply verifies that all of the manifest files are present. The contents are trusted to be correct as per `test_manifests.py`.

I recommend reading commit by commit.

### CODE REVIEW

**Review by satra — APPROVED** [review]
i went through all the commits and the logic LGTM. i didn't see any test output on our staging s3 bucket. should i try on some dandiset in staging?

**Comment by dchiquito** [comment]
@satra The staging environment is based off of `master`, so this PR needs to be merged before it is applied to staging.
I just did that, so you should be good to test it on staging now.

**Comment by satra** [comment]
@dchiquito - was going to try this out, but ran into an issue where the dandiset is not valid:

image

however, as you can see it does have a license field in the metadata. are the validation jobs being run?

**Comment by dchiquito** [comment]
@satra the validation jobs should be all caught up now.

**Comment by dchiquito** [comment]
I published https://gui-staging.dandiarchive.org/#/dandiset/000001/0.210720.2058 and it has all the correct .jsonld manifests. You should be able to use that to test.

**Comment by satra** [comment]
@dchiquito - the output looks good to me. the only minor thing i spotted was that the timestamps anywhere did not have time zone info.  i'll file another issue for that.

**Pull request merged**
