### PR TITLE
make dois published

### PR DESCRIPTION
**Pull request by satra**
https://support.datacite.org/docs/api-create-dois#create-a-findable-doi

this needs to be augmented such that we don't do this in tests but only for actual dandisets.

### CODE REVIEW

**Comment by satra** [comment]
@dchiquito - the current dois from staging are set in draft mode, we should make them findable.  however, we don't really want this to happen for every doi. since a doi in registered/findable mode cannot be deleted. so this should only happen when we publish from the production server. so ideally some environment flag that says that code is being executed in a production environment.

**Comment by yarikoptic** [comment]
AFAIK (see https://github.com/dandi/dandi-api/issues/181#issuecomment-877485448) new ones should be Findable (since we had some recent ones as Findable), but I could be wrong

**Comment by yarikoptic** [comment]
or in other words: how did we end up with Finable DOIs in test. datacite without this change?

**Comment by dchiquito** [comment]
I created a few findable ones manually when I was experimenting with the API before I fully understood the distinction.

IIRC dandischema needs to include `"event": "publish"` in the DOI data returned from to_datacite: https://support.datacite.org/docs/api-create-dois#create-a-findable-doi Probably an argument `publish = False` would include it if True and omit it if False.

Once that's there I can add a setting and call to_datacite with the correct arguments.

**Comment by dchiquito** [comment]
I did the dandischema work in https://github.com/dandi/dandischema/pull/70

**Comment by dchiquito** [comment]
I'm going to close this PR and move the discussion to https://github.com/dandi/dandischema/pull/70

**Comment by satra** [comment]
the dandischema PR merged and released. but it would still require a change in the API server to actually publish only on the production server.

**Comment by dchiquito** [comment]
https://github.com/dandi/dandi-api/pull/451 is that change. https://github.com/dandi/dandi-infrastructure/pull/87 turns that setting on in production only.

**Pull request closed without merging**
