### PR TITLE
Collect first and last names from users who don't have them

### LINKED ISSUE #570: Collect full names for nameless users
This needs to be done after #564 is completed, since solving that issue will mean all new users come with names.

One way to accomplish this is to check for blank name fields for any existing user, and redirect them to a form that is similar to the questionnaire of #564, but that just asks for their name.

### PR DESCRIPTION
**Pull request by mvandenburgh**
This is one potential solution to #570.

This adds a check to the `oauth/authorize` endpoint that is called whenever a user logs in. If the user doesn't have a first or last name, they are redirected to a form that they must fill out before being allowed to log in. This would need to be accompanied by a manual operation to revoke all session cookies from users without first or last names.

Closes #570

### CODE REVIEW

**Review by waxlamp — APPROVED** [review]
This is a good approach. I would do the following before merging:

- [x] Add an "escape hatch" for users to send us an email (`Contact us if you have any questions` would be good text for that part)
- [x] File follow-on issues to
  - write a maintenance script to revoke logins for name-free users
  - cause validation to fail for empty-named contact person or contributors

**Review by dchiquito — COMMENTED** [review]
Is there any reason not to just use the full questionnaire? I guess it would be slightly more convenient for the users to only fill out their names, but it's more plumbing for us, and we would probably want to have a full questionnaire for old users eventually.

**Comment by mvandenburgh** [comment]
> Is there any reason not to just use the full questionnaire? I guess it would be slightly more convenient for the users to only fill out their names, but it's more plumbing for us, and we would probably want to have a full questionnaire for old users eventually.

Yeah it was just a convenience thing. I'm on board with using the full questionnaire if that's not an issue, it would certainly make this code less complicated.

**Comment by waxlamp** [comment]
> > Is there any reason not to just use the full questionnaire? I guess it would be slightly more convenient for the users to only fill out their names, but it's more plumbing for us, and we would probably want to have a full questionnaire for old users eventually.
> 
> Yeah it was just a convenience thing. I'm on board with using the full questionnaire if that's not an issue, it would certainly make this code less complicated.

This is a question for @satra and @yarikoptic. My own opinion is to grandfather in users who are already approved, which is why we're going out of our way to just collect the names in this case. I agree it would be less work for us to throw the full questionnaire at these users, but the ultimate goal is to make this system useful and easy for users (which may sometimes require us to do more work).

**Comment by satra** [comment]
i think the eventual solution is a user profile panel + richer user data model with links to github, orcid, etc.,. for now grandfathering and using the full questionnaire sounds good.

**Comment by waxlamp** [comment]
To be clear: we can use the full questionnaire, but we won't change any user's approved status based on what they supply (to me, that's what "grandfathered" means in this context). Is that right?

This way we can reduce the burden on our devs while still collecting the full name information we need.

**Comment by satra** [comment]
The only place where this will get used is the user icon and in any subsequent emails to users. There are no other places where this information is currently used. since this is only for user registration, anyone who has already registered can be grandfathered in.

**Comment by waxlamp** [comment]
> The only place where this will get used is the user icon and in any subsequent emails to users. There are no other places where this information is currently used. since this is only for user registration, anyone who has already registered can be grandfathered in.

The driving reason we're adding it is to prevent empty Contact Person fields in new dandisets created by users without a name set. This is why we need names from approved users who don't have one set, and also why I'm worrying about presenting a full questionnaire to approved users when we only need their name.

**Comment by satra** [comment]
Contact person doesn't come from a user's/owner credentials. It comes from
the contactperson set up in the contributor list. Hence this should be more
of a dandiset creation thing than a user registration thing. Contact person
may be someone other than the owner it any owners.

**Comment by waxlamp** [comment]
> Contact person doesn't come from a user's/owner credentials. It comes from the contactperson set up in the contributor list. Hence this should be more of a dandiset creation thing than a user registration thing. Contact person may be someone other than the owner it any owners.

Agreed, but by default the creator of the dandiset is listed as the initial contact person, which leaves the dandiset broken for nameless users. I just filed an issue to disallow empty contact person fields as part of validation, but it would still be good to have the users' names (for this purpose, but also the others you noted).

In the large, this discussion still leaves open my original question, which is whether we can simply ask approved users for their names, rather than showing them the full questionnaire.

**Comment by satra** [comment]
> I just filed an issue to disallow empty contact person fields as part of validation,

this is already true and checked by the validator.

i'm fine with asking users for their names when they log in.

**Comment by waxlamp** [comment]
> > I just filed an issue to disallow empty contact person fields as part of validation,
> 
> this is already true and checked by the validator.
> 

Looking at [164](https://gui.dandiarchive.org/#/dandiset/000164), notice that the contact person is blank, but the validation errors do not point that out. Technically, you are right: the contact person here is listed as a single comma (`,`), which the regex currently recognizes as non-empty, but I'm suggesting that a contact person should have non-empty first and last names.

> i'm fine with asking users for their names when they log in.

Excellent, thanks!

**Comment by satra** [comment]
indeed this is a validation issue, the regex is not write. this will require a schema update, which means the metadata update issue comes into play.

**Review by dchiquito — APPROVED** [review]

**Pull request merged**
