### PR TITLE
BF: total size by asking for unique blobs associated with some version

### LINKED ISSUE #260: Discrepancy between size estimates/calculations
when i use the stats api, i get:
```
{
"dandiset_count":65
"published_dandiset_count":0
"user_count":66
"size":16363640643492
}
```
when i sum all the content of the size of dandisets by going through, i get:
15414647730404

```python
import requests
url = "https://api.dandiarchive.org/api/dandisets/?page_size=100"
response = requests.request("GET", url)
dandisets = response.json()["results"]
ds = []
for val in dandisets:
    ds.append({"identifier": val["identifier"], "size": val["draft_version"]["size"], 
               "updated": val["draft_version"]["modified"]})
df = pd.DataFrame(ds)
df["size"].sum()
```

### PR DESCRIPTION
**Pull request by yarikoptic**
Closes #260

### CODE REVIEW

**Comment by yarikoptic** [comment]
well, tests pass.  Since no coverage report I have no clue if tests cover that code path. So it would need knowledgeable reviewer to see if what I have done makes any sense/has hope to work.

**Comment by yarikoptic** [comment]
woohoo -- with a local instance running where I created two dandisets to which I uploaded the same singular asset from 000027, `master` version:
```
$> curl -X GET "http://127.0.0.1:8000/api/stats/" -H  "accept: application/json" 
{"dandiset_count":2,"published_dandiset_count":0,"user_count":5,"size":37584}%  
```
and this PR:
```
$> curl -X GET "http://127.0.0.1:8000/api/stats/" -H "accept: application/json"
{"dandiset_count":2,"published_dandiset_count":0,"user_count":5,"size":18792}%
```
which 1. does not crash! 2. reflects reality;

then I replaced that file with another one of size `148880` in one of the dataset.  This branch
```
$> curl -X GET "http://127.0.0.1:8000/api/stats/" -H "accept: application/json"
{"dandiset_count":2,"published_dandiset_count":0,"user_count":5,"size":167672}%   
```
which is correct (148880 + 18792) and master
```
$> curl -X GET "http://127.0.0.1:8000/api/stats/" -H "accept: application/json"
{"dandiset_count":2,"published_dandiset_count":0,"user_count":5,"size":186464}%    
```
is wrong. then I replaced asset in the other dandiset with the same blob. `master`:
```
$> curl -X GET "http://127.0.0.1:8000/api/stats/" -H "accept: application/json"
{"dandiset_count":2,"published_dandiset_count":0,"user_count":5,"size":335344}%  
```
and this 
```
$> curl -X GET "http://127.0.0.1:8000/api/stats/" -H "accept: application/json"
{"dandiset_count":2,"published_dandiset_count":0,"user_count":5,"size":167672}% 
```
which is odd since I expected it to go back to 148880 since original blob was replaced in both dandisets ... khm.

**Comment by yarikoptic** [comment]
pushed the fix for that, and now it reports:
```
$> curl -X GET "http://127.0.0.1:8000/api/stats/" -H "accept: application/json"
{"dandiset_count":2,"published_dandiset_count":0,"user_count":5,"size":148880}
```

so I think it is working.  will merge monday if no objections or further comments

**Comment by yarikoptic** [comment]
finally the test has failed and it should have -- that asset is loose , i.e. not linked to any Version

**Comment by yarikoptic** [comment]
@satra -- have a look - is that how we want to count/report the total size -- as an amount of unique "addressable" (from datasets) blobs?

**Comment by satra** [comment]
@yarikoptic - looks good to me as long as `blob__id` is `dandi-etag` ?

**Comment by satra** [comment]
or there is a one to one mapping.

**Comment by yarikoptic** [comment]
good point, I would assume so since we deduplicate blobs.
Note: @dchiquito is doing his own version of a fix in #307

**Pull request closed without merging**
