### PR TITLE
Remove Girder code from API

### PR DESCRIPTION
**Pull request by jwodder**
The Girder code in dandiapi appears to be unused, and it needs to be removed so that the Docker test setup in dandi-cli can get rid of the Girder containers.

### CODE REVIEW

**Comment by yarikoptic** [comment]
@dandi/dandiarchive please let us know if anything else is needed for this to land

**Comment by waxlamp** [comment]
@dchiquito is out today, but he's aware of the refactoring that needs to be done to excise Girder3 from the various codebases. It's up there on his list along with publish workflow. Please wait for his (and/or @AlmightyYakob's) review before merging.

**Comment by AlmightyYakob** [comment]
Are the migration scripts still needed? If not there's still girder specific code in the `scripts` folder, as well as the `girder-client` dependency in `setup.py`.

**Comment by yarikoptic** [comment]
is this one superseded by #272 @dchiquito ?

**Review by brianhelba — APPROVED** [review]

**Review by dchiquito — APPROVED** [review]

**Pull request merged**
